#!/usr/bin/env python3
"""Compile fixed OMR exam/area presets into SVG outlines; no runtime text/fonts.

python3 tools/build_omr_headings.py --font NotoSansCJK-Medium.ttc
The pinned source's Korean face is used, under SIL OFL 1.1.
"""
import argparse
import hashlib
from pathlib import Path
from xml.sax.saxutils import escape
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen

ROOT = Path(__file__).resolve().parents[1]
FONT_SHA256 = '197d5e1e019faca33a4d55931c7d68b8056f3b97cb862049f5cb8de9efdfb8ce'
EXAMS = {'csat': '학년도 대학수학능력시험 답안지',
         'm6': '학년도 대학수학능력시험 6월 모의평가 답안지',
         'm9': '학년도 대학수학능력시험 9월 모의평가 답안지',
         **{f'edu{m}': f'년 {m}월 전국연합학력평가 답안지' for m in (3,4,5,6,7,9,10,11)},
         'other': '년 답안지'}
AREAS = {'social': '사회탐구 영역', 'science': '과학탐구 영역', 'vocational': '직업탐구 영역'}


def build(font_path):
    if hashlib.sha256(font_path.read_bytes()).hexdigest() != FONT_SHA256:
        raise ValueError('Source font SHA-256 mismatch')
    font = TTFont(font_path, fontNumber=1)
    glyphs, cmap = font.getGlyphSet(), font.getBestCmap()
    upm = font['head'].unitsPerEm
    texts = list(EXAMS.values()) + list(AREAS.values()) + ['0123456789']
    chars = sorted(set(''.join(texts)) - {' '})
    defs = []
    for ch in chars:
        if ord(ch) not in cmap:
            raise ValueError(f'Missing glyph: {ch}')
        pen = SVGPathPen(glyphs); glyphs[cmap[ord(ch)]].draw(pen)
        defs.append(f'<path id="g{ord(ch):x}" d="{pen.getCommands()}"/>')

    def words(text):
        x, paths = 0, []
        for ch in text:
            if ch != ' ':
                paths.append(f'<use href="#g{ord(ch):x}" transform="translate({x} 0)"/>')
            x += font['hmtx'][cmap[ord(ch)]][0]
        return ''.join(paths), x

    for digit in '0123456789':
        path, width = words(digit)
        defs.append(f'<symbol id="year-{digit}" viewBox="0 0 34 80"><g transform="translate(0 68) scale({60/upm} {-70/upm})">{path}</g></symbol>')
    for key, text in EXAMS.items():
        path, width = words(text)
        sx = min(60/upm, 1245/width)
        defs.append(f'<symbol id="exam-{key}" viewBox="0 0 1400 80"><title>{escape(text)}</title><g transform="translate(140 68) scale({sx:.8f} {-70/upm})">{path}</g></symbol>')
    for key, text in AREAS.items():
        path, width = words(text)
        sx = min(95/upm, 520/width)
        defs.append(f'<symbol id="area-{key}" viewBox="0 0 560 110"><g transform="translate(12 96) scale({sx:.8f} {-100/upm})">{path}</g></symbol>')
    font.close()
    return ('<svg xmlns="http://www.w3.org/2000/svg"><!-- Noto Sans CJK KR Medium; SIL OFL 1.1. '
            f'Source SHA-256 {FONT_SHA256}. Generated by tools/build_omr_headings.py. -->'
            '<defs fill="currentColor">' + ''.join(defs) + '</defs></svg>\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--font', type=Path, required=True)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    target = ROOT/'omr/headings.svg'; result = build(args.font)
    if args.check:
        if target.read_text() != result:
            raise SystemExit('OMR heading presets differ')
    else:
        target.write_text(result)
    print('OMR heading presets match' if args.check else f'Wrote {target.relative_to(ROOT)} ({len(result.encode())} bytes)')


if __name__ == '__main__':
    main()
